-- Staging schema for the quotation app. No production cutover.

-- source_rowid retains SQLite pagination order; do not regenerate on import.

CREATE TABLE IF NOT EXISTS "staff_auth_attempts" (
  "key" TEXT NOT NULL,
  "count" BIGINT NOT NULL,
  "expires" BIGINT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("key")
);

CREATE TABLE IF NOT EXISTS "contract_counters" (
  "id" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "year" BIGINT NOT NULL,
  "month" BIGINT NOT NULL,
  "legal_entity" TEXT NOT NULL,
  "last_sequence" BIGINT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "contract_document_numbers" (
  "quote_number" TEXT NOT NULL,
  "legal_entity" TEXT NOT NULL,
  "contract_number" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("quote_number","legal_entity")
);

CREATE TABLE IF NOT EXISTS "contract_statuses" (
  "quote_number" TEXT NOT NULL,
  "contract_number" TEXT,
  "status" TEXT NOT NULL,
  "crm_row_id" TEXT,
  "crm_url" TEXT,
  "customer_name" TEXT,
  "item_count" BIGINT,
  "message" TEXT,
  "result_json" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("quote_number")
);

CREATE TABLE IF NOT EXISTS "contract_transfers" (
  "quote_number" TEXT NOT NULL,
  "contract_number" TEXT NOT NULL,
  "contract_url" TEXT,
  "message" TEXT NOT NULL,
  "result_json" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("quote_number")
);

CREATE TABLE IF NOT EXISTS "staff_credentials" (
  "member_id" TEXT NOT NULL,
  "password_hash" TEXT,
  "activation_hash" TEXT,
  "activation_expires" BIGINT,
  "version" BIGINT NOT NULL DEFAULT 0,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("member_id")
);

CREATE TABLE IF NOT EXISTS "crm_tasks" (
  "id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "details" TEXT NOT NULL DEFAULT '',
  "customer_id" TEXT,
  "quote_number" TEXT,
  "status" TEXT NOT NULL DEFAULT 'open',
  "priority" TEXT NOT NULL DEFAULT 'normal',
  "due_date" TEXT,
  "assigned_to" TEXT NOT NULL,
  "created_by" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "completed_at" TEXT,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "customer_contract_profiles" (
  "customer_id" TEXT NOT NULL,
  "data" TEXT NOT NULL DEFAULT '{}',
  "updated_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("customer_id")
);

CREATE TABLE IF NOT EXISTS "sapo_customers" (
  "created_at" TEXT NOT NULL DEFAULT '',
  "tax_code" TEXT NOT NULL DEFAULT '',
  "customer_code" TEXT NOT NULL DEFAULT '',
  "discounts" TEXT NOT NULL DEFAULT '{}',
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "contact" TEXT NOT NULL,
  "phone" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "address" TEXT NOT NULL,
  "search" TEXT NOT NULL,
  "source_version" BIGINT NOT NULL,
  "synced_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "staff_members" (
  "id" TEXT NOT NULL,
  "identity_id" TEXT,
  "phone" TEXT NOT NULL DEFAULT '',
  "email" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "role" TEXT NOT NULL DEFAULT 'employee',
  "position_id" TEXT,
  "active" BIGINT NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "staff_notification_reads" (
  "notification_id" TEXT NOT NULL,
  "member_id" TEXT NOT NULL,
  "read_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE
);

CREATE TABLE IF NOT EXISTS "staff_positions" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "product_edits" (
  "sku" TEXT NOT NULL,
  "data" TEXT NOT NULL,
  "revision" BIGINT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "updated_by" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("sku")
);

CREATE TABLE IF NOT EXISTS "staff_quotations" (
  "id" TEXT NOT NULL,
  "creator_id" TEXT NOT NULL,
  "quote_no" TEXT NOT NULL,
  "quote_type" TEXT NOT NULL,
  "customer" TEXT NOT NULL,
  "quote_date" TEXT,
  "search_text" TEXT,
  "contract_number" TEXT,
  "contract_quote_no" TEXT,
  "has_contract" BIGINT NOT NULL DEFAULT 0,
  "data" TEXT NOT NULL,
  "revision" BIGINT NOT NULL DEFAULT 1,
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "staff_quote_notifications" (
  "id" TEXT NOT NULL,
  "quote_id" TEXT NOT NULL,
  "actor_id" TEXT NOT NULL,
  "event_type" TEXT NOT NULL,
  "quote_no" TEXT NOT NULL,
  "customer" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "sapo_order_statuses" (
  "quote_number" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "sapo_order_id" TEXT,
  "sapo_order_code" TEXT,
  "sapo_order_url" TEXT,
  "customer_name" TEXT,
  "message" TEXT,
  "payload_json" TEXT,
  "updated_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("quote_number")
);

CREATE TABLE IF NOT EXISTS "staff_sessions" (
  "hash" TEXT NOT NULL,
  "member_id" TEXT NOT NULL,
  "version" BIGINT NOT NULL,
  "expires" BIGINT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("hash")
);

CREATE TABLE IF NOT EXISTS "staff_setup" (
  "id" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "staff_sapo_links" (
  "sapo_id" TEXT NOT NULL,
  "member_id" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "evidence" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("sapo_id")
);

CREATE TABLE IF NOT EXISTS "stock_imports" (
  "revision" BIGINT NOT NULL,
  "key" TEXT NOT NULL,
  "filename" TEXT NOT NULL,
  "observed_at" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "created_by" TEXT NOT NULL,
  "count" BIGINT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("revision")
);

CREATE TABLE IF NOT EXISTS "vigifts_appsheet_actions" (
  "app_id" TEXT NOT NULL,
  "action_name" TEXT NOT NULL,
  "display_name" TEXT NOT NULL DEFAULT '',
  "table_name" TEXT NOT NULL DEFAULT '',
  "action_type" TEXT NOT NULL DEFAULT '',
  "icon" TEXT NOT NULL DEFAULT '',
  "condition" TEXT,
  "modifies_data" BIGINT NOT NULL DEFAULT 0,
  "action_json" TEXT NOT NULL DEFAULT '{}',
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("app_id","action_name","table_name")
);

CREATE TABLE IF NOT EXISTS "vigifts_appsheet_apps" (
  "id" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "source_app_id" TEXT NOT NULL,
  "source_version" TEXT NOT NULL DEFAULT '',
  "app_definition_json" TEXT NOT NULL,
  "exported_at" TEXT NOT NULL,
  "imported_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "vigifts_appsheet_bots" (
  "app_id" TEXT NOT NULL,
  "bot_name" TEXT NOT NULL,
  "event_name" TEXT NOT NULL DEFAULT '',
  "process_name" TEXT NOT NULL DEFAULT '',
  "disabled" BIGINT NOT NULL DEFAULT 0,
  "bot_json" TEXT NOT NULL DEFAULT '{}',
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("app_id","bot_name")
);

CREATE TABLE IF NOT EXISTS "vigifts_appsheet_fields" (
  "app_id" TEXT NOT NULL,
  "table_name" TEXT NOT NULL,
  "field_id" TEXT NOT NULL,
  "field_name" TEXT NOT NULL,
  "field_type" TEXT NOT NULL DEFAULT '',
  "ordinal" BIGINT NOT NULL DEFAULT 0,
  "is_key" BIGINT NOT NULL DEFAULT 0,
  "is_label" BIGINT NOT NULL DEFAULT 0,
  "is_required" BIGINT NOT NULL DEFAULT 0,
  "is_hidden" BIGINT NOT NULL DEFAULT 0,
  "is_virtual" BIGINT NOT NULL DEFAULT 0,
  "expression_json" TEXT NOT NULL DEFAULT '{}',
  "field_json" TEXT NOT NULL DEFAULT '{}',
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("app_id","table_name","field_id")
);

CREATE TABLE IF NOT EXISTS "vigifts_appsheet_rows" (
  "app_id" TEXT NOT NULL,
  "table_name" TEXT NOT NULL,
  "tuple_id" TEXT NOT NULL,
  "values_json" TEXT NOT NULL,
  "raw_json" TEXT NOT NULL DEFAULT '{}',
  "search_text" TEXT NOT NULL DEFAULT '',
  "source_created_at" TEXT,
  "source_updated_at" TEXT,
  "imported_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("app_id","table_name","tuple_id")
);

CREATE TABLE IF NOT EXISTS "vigifts_appsheet_tables" (
  "app_id" TEXT NOT NULL,
  "table_name" TEXT NOT NULL,
  "safe_name" TEXT NOT NULL,
  "base_id" TEXT NOT NULL,
  "frame_id" TEXT NOT NULL,
  "schema_name" TEXT NOT NULL,
  "update_mode" BIGINT NOT NULL DEFAULT 0,
  "allowed_updates" BIGINT NOT NULL DEFAULT 0,
  "source_json" TEXT NOT NULL DEFAULT '{}',
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("app_id","table_name")
);

CREATE TABLE IF NOT EXISTS "vigifts_appsheet_views" (
  "app_id" TEXT NOT NULL,
  "view_name" TEXT NOT NULL,
  "display_name" TEXT NOT NULL DEFAULT '',
  "position" TEXT NOT NULL DEFAULT '',
  "table_name" TEXT NOT NULL DEFAULT '',
  "action" TEXT NOT NULL DEFAULT '',
  "action_type" TEXT NOT NULL DEFAULT '',
  "view_order" BIGINT NOT NULL DEFAULT 0,
  "show_if" TEXT,
  "view_json" TEXT NOT NULL DEFAULT '{}',
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("app_id","view_name")
);

CREATE TABLE IF NOT EXISTS "staff_web_notification_reads" (
  "notification_id" TEXT NOT NULL,
  "member_id" TEXT NOT NULL,
  "read_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("notification_id","member_id")
);

CREATE TABLE IF NOT EXISTS "staff_web_notifications" (
  "id" TEXT NOT NULL,
  "event_type" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "body" TEXT NOT NULL,
  "url" TEXT NOT NULL,
  "target_role" TEXT DEFAULT 'manager',
  "target_member_id" TEXT,
  "actor_id" TEXT,
  "data_json" TEXT NOT NULL DEFAULT '{}',
  "created_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "staff_web_push_subscriptions" (
  "id" TEXT NOT NULL,
  "member_id" TEXT NOT NULL,
  "endpoint" TEXT NOT NULL,
  "p256dh" TEXT NOT NULL,
  "auth" TEXT NOT NULL,
  "user_agent" TEXT NOT NULL DEFAULT '',
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "last_seen_at" TEXT,
  "disabled_at" TEXT,
  "failure_count" BIGINT NOT NULL DEFAULT 0,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "work_assignments" (
  "member_id" TEXT NOT NULL,
  "branch_id" TEXT NOT NULL,
  "sapo_account_id" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("member_id","branch_id")
);

CREATE TABLE IF NOT EXISTS "work_audit" (
  "id" TEXT NOT NULL,
  "entity_id" TEXT NOT NULL,
  "actor_id" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "data" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "work_branches" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "keeper_id" TEXT,
  "updated_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "work_cash_requests" (
  "id" TEXT NOT NULL,
  "shift_id" TEXT NOT NULL,
  "member_id" TEXT NOT NULL,
  "kind" TEXT NOT NULL,
  "amount" BIGINT NOT NULL,
  "note" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "reviewed_by" TEXT,
  "review_note" TEXT NOT NULL DEFAULT '',
  "created_at" TEXT NOT NULL,
  "updated_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "work_reports" (
  "id" TEXT NOT NULL,
  "shift_id" TEXT NOT NULL,
  "member_id" TEXT NOT NULL,
  "position_id" TEXT NOT NULL,
  "phase" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'draft',
  "data" TEXT NOT NULL,
  "snapshot" TEXT NOT NULL DEFAULT '{}',
  "revision" BIGINT NOT NULL DEFAULT 1,
  "updated_at" TEXT NOT NULL,
  "submitted_at" TEXT,
  "reviewed_by" TEXT,
  "review_note" TEXT NOT NULL DEFAULT '',
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "work_shifts" (
  "id" TEXT NOT NULL,
  "branch_id" TEXT NOT NULL,
  "work_date" TEXT NOT NULL,
  "starts_at" TEXT NOT NULL,
  "ends_at" TEXT NOT NULL,
  "label" TEXT NOT NULL,
  "keeper_id" TEXT,
  "opening" BIGINT,
  "actual" BIGINT,
  "expected" BIGINT,
  "difference" BIGINT,
  "cash_status" TEXT NOT NULL DEFAULT 'not_opened',
  "data" TEXT NOT NULL DEFAULT '{}',
  "revision" BIGINT NOT NULL DEFAULT 1,
  "updated_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "work_snapshots" (
  "id" TEXT NOT NULL,
  "shift_id" TEXT NOT NULL,
  "member_id" TEXT NOT NULL,
  "data" TEXT NOT NULL,
  "created_at" TEXT NOT NULL,
  "source_rowid" BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS printing_workshops (id TEXT PRIMARY KEY,name TEXT NOT NULL,name_key TEXT NOT NULL UNIQUE,tax_code TEXT NOT NULL DEFAULT '',address TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '',email TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,created_by TEXT NOT NULL,source_rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE IF NOT EXISTS sapo_runtime_sessions (id TEXT PRIMARY KEY,encrypted_cookie TEXT NOT NULL,updated_at TEXT NOT NULL,updated_by TEXT NOT NULL,source_rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

CREATE TABLE IF NOT EXISTS vigifts_product_image_map (product_id TEXT PRIMARY KEY,sku TEXT NOT NULL,product_name TEXT NOT NULL,image_file_name TEXT NOT NULL,image_source_path TEXT NOT NULL,image_url TEXT,sync_status TEXT NOT NULL,imported_at TEXT NOT NULL,source_rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE);

ALTER TABLE "staff_credentials" ADD CONSTRAINT "staff_credentials_member_id_staff_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "staff_members" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "customer_contract_profiles" ADD CONSTRAINT "customer_contract_profiles_customer_id_sapo_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "sapo_customers" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staff_members" ADD CONSTRAINT "staff_members_position_id_staff_positions_id_fk" FOREIGN KEY ("position_id") REFERENCES "staff_positions" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staff_notification_reads" ADD CONSTRAINT "staff_notification_reads_notification_id_staff_quote_notifications_id_fk" FOREIGN KEY ("notification_id") REFERENCES "staff_quote_notifications" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staff_notification_reads" ADD CONSTRAINT "staff_notification_reads_member_id_staff_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "staff_members" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staff_quotations" ADD CONSTRAINT "staff_quotations_creator_id_staff_members_id_fk" FOREIGN KEY ("creator_id") REFERENCES "staff_members" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staff_quote_notifications" ADD CONSTRAINT "staff_quote_notifications_quote_id_staff_quotations_id_fk" FOREIGN KEY ("quote_id") REFERENCES "staff_quotations" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staff_quote_notifications" ADD CONSTRAINT "staff_quote_notifications_actor_id_staff_members_id_fk" FOREIGN KEY ("actor_id") REFERENCES "staff_members" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staff_sessions" ADD CONSTRAINT "staff_sessions_member_id_staff_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "staff_members" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staff_sapo_links" ADD CONSTRAINT "staff_sapo_links_member_id_staff_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "staff_members" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "vigifts_appsheet_actions" ADD CONSTRAINT "vigifts_appsheet_actions_app_id_vigifts_appsheet_apps_id_fk" FOREIGN KEY ("app_id") REFERENCES "vigifts_appsheet_apps" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "vigifts_appsheet_bots" ADD CONSTRAINT "vigifts_appsheet_bots_app_id_vigifts_appsheet_apps_id_fk" FOREIGN KEY ("app_id") REFERENCES "vigifts_appsheet_apps" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "vigifts_appsheet_fields" ADD CONSTRAINT "vigifts_appsheet_fields_app_id_vigifts_appsheet_apps_id_fk" FOREIGN KEY ("app_id") REFERENCES "vigifts_appsheet_apps" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "vigifts_appsheet_rows" ADD CONSTRAINT "vigifts_appsheet_rows_app_id_vigifts_appsheet_apps_id_fk" FOREIGN KEY ("app_id") REFERENCES "vigifts_appsheet_apps" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "vigifts_appsheet_tables" ADD CONSTRAINT "vigifts_appsheet_tables_app_id_vigifts_appsheet_apps_id_fk" FOREIGN KEY ("app_id") REFERENCES "vigifts_appsheet_apps" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "vigifts_appsheet_views" ADD CONSTRAINT "vigifts_appsheet_views_app_id_vigifts_appsheet_apps_id_fk" FOREIGN KEY ("app_id") REFERENCES "vigifts_appsheet_apps" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staff_web_notification_reads" ADD CONSTRAINT "staff_web_notification_reads_notification_id_staff_web_notifications_id_fk" FOREIGN KEY ("notification_id") REFERENCES "staff_web_notifications" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staff_web_notification_reads" ADD CONSTRAINT "staff_web_notification_reads_member_id_staff_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "staff_members" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staff_web_notifications" ADD CONSTRAINT "staff_web_notifications_actor_id_staff_members_id_fk" FOREIGN KEY ("actor_id") REFERENCES "staff_members" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "staff_web_push_subscriptions" ADD CONSTRAINT "staff_web_push_subscriptions_member_id_staff_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "staff_members" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "work_assignments" ADD CONSTRAINT "work_assignments_member_id_staff_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "staff_members" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "work_assignments" ADD CONSTRAINT "work_assignments_branch_id_work_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "work_branches" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "work_cash_requests" ADD CONSTRAINT "work_cash_requests_shift_id_work_shifts_id_fk" FOREIGN KEY ("shift_id") REFERENCES "work_shifts" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "work_cash_requests" ADD CONSTRAINT "work_cash_requests_member_id_staff_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "staff_members" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "work_reports" ADD CONSTRAINT "work_reports_shift_id_work_shifts_id_fk" FOREIGN KEY ("shift_id") REFERENCES "work_shifts" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "work_reports" ADD CONSTRAINT "work_reports_member_id_staff_members_id_fk" FOREIGN KEY ("member_id") REFERENCES "staff_members" ("id") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "work_shifts" ADD CONSTRAINT "work_shifts_branch_id_work_branches_id_fk" FOREIGN KEY ("branch_id") REFERENCES "work_branches" ("id") DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX IF NOT EXISTS "idx_attempts_expires" ON "staff_auth_attempts" ("expires");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_contract_counters_period" ON "contract_counters" ("type","year","month","legal_entity");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_contract_document_number" ON "contract_document_numbers" ("contract_number");

CREATE INDEX IF NOT EXISTS "idx_contract_statuses_updated" ON "contract_statuses" ("updated_at");

CREATE INDEX IF NOT EXISTS "idx_contract_transfers_updated" ON "contract_transfers" ("updated_at");

CREATE INDEX IF NOT EXISTS "idx_crm_tasks_assignee_status" ON "crm_tasks" ("assigned_to","status");

CREATE INDEX IF NOT EXISTS "idx_crm_tasks_due_date" ON "crm_tasks" ("due_date");

CREATE INDEX IF NOT EXISTS "idx_customer_contract_profiles_updated" ON "customer_contract_profiles" ("updated_at");

CREATE INDEX IF NOT EXISTS "idx_sapo_customers_name" ON "sapo_customers" ("name");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_members_email" ON "staff_members" ("email");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_members_identity" ON "staff_members" ("identity_id");

CREATE INDEX IF NOT EXISTS "idx_members_position" ON "staff_members" ("position_id");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_notification_reads" ON "staff_notification_reads" ("notification_id","member_id");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_positions_name" ON "staff_positions" ("name");

CREATE INDEX IF NOT EXISTS "idx_quotations_creator_updated" ON "staff_quotations" ("creator_id","updated_at");

CREATE INDEX IF NOT EXISTS "idx_quotations_created" ON "staff_quotations" ("created_at");

CREATE INDEX IF NOT EXISTS "idx_quotations_quote_date" ON "staff_quotations" ("quote_date");

CREATE INDEX IF NOT EXISTS "idx_quotations_contract" ON "staff_quotations" ("contract_number");

CREATE INDEX IF NOT EXISTS "idx_quotations_has_contract" ON "staff_quotations" ("has_contract","created_at");

CREATE INDEX IF NOT EXISTS "idx_quote_notifications_created" ON "staff_quote_notifications" ("created_at");

CREATE INDEX IF NOT EXISTS "idx_sapo_order_statuses_updated" ON "sapo_order_statuses" ("updated_at");

CREATE INDEX IF NOT EXISTS "idx_sessions_member" ON "staff_sessions" ("member_id");

CREATE INDEX IF NOT EXISTS "idx_sessions_expires" ON "staff_sessions" ("expires");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_staff_sapo_member" ON "staff_sapo_links" ("member_id");

CREATE INDEX IF NOT EXISTS "idx_vigifts_actions_table" ON "vigifts_appsheet_actions" ("app_id","table_name");

CREATE INDEX IF NOT EXISTS "idx_vigifts_bots_disabled" ON "vigifts_appsheet_bots" ("app_id","disabled");

CREATE INDEX IF NOT EXISTS "idx_vigifts_fields_name" ON "vigifts_appsheet_fields" ("app_id","table_name","field_name");

CREATE INDEX IF NOT EXISTS "idx_vigifts_rows_table" ON "vigifts_appsheet_rows" ("app_id","table_name");

CREATE INDEX IF NOT EXISTS "idx_vigifts_rows_search" ON "vigifts_appsheet_rows" ("search_text");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_vigifts_tables_frame" ON "vigifts_appsheet_tables" ("app_id","frame_id");

CREATE INDEX IF NOT EXISTS "idx_vigifts_tables_safe" ON "vigifts_appsheet_tables" ("safe_name");

CREATE INDEX IF NOT EXISTS "idx_vigifts_views_position" ON "vigifts_appsheet_views" ("app_id","position","view_order");

CREATE INDEX IF NOT EXISTS "idx_web_notifications_created" ON "staff_web_notifications" ("created_at");

CREATE INDEX IF NOT EXISTS "idx_web_notifications_target" ON "staff_web_notifications" ("target_role","target_member_id","created_at");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_web_push_endpoint" ON "staff_web_push_subscriptions" ("endpoint");

CREATE INDEX IF NOT EXISTS "idx_web_push_member" ON "staff_web_push_subscriptions" ("member_id","disabled_at");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_work_branch_account" ON "work_assignments" ("branch_id","sapo_account_id");

CREATE INDEX IF NOT EXISTS "idx_work_audit_entity" ON "work_audit" ("entity_id","created_at");

CREATE INDEX IF NOT EXISTS "idx_work_cash_requests_shift" ON "work_cash_requests" ("shift_id","status");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_work_report_once" ON "work_reports" ("shift_id","member_id","phase");

CREATE INDEX IF NOT EXISTS "idx_work_reports_member" ON "work_reports" ("member_id","updated_at");

CREATE INDEX IF NOT EXISTS "idx_work_reports_status" ON "work_reports" ("status","updated_at");

CREATE UNIQUE INDEX IF NOT EXISTS "idx_work_shift_period" ON "work_shifts" ("branch_id","starts_at","ends_at");

CREATE INDEX IF NOT EXISTS "idx_work_branch_time" ON "work_shifts" ("branch_id","ends_at");

CREATE INDEX IF NOT EXISTS "idx_work_snapshot_owner" ON "work_snapshots" ("member_id","shift_id","created_at");

CREATE INDEX IF NOT EXISTS idx_vigifts_product_image_map_sku ON vigifts_product_image_map(sku);

CREATE INDEX IF NOT EXISTS idx_quotations_quote_number_lower ON staff_quotations(lower(quote_no));
