import test from 'node:test';
import assert from 'node:assert/strict';
import {mediaSources,rewriteMedia,mediaId,copyMedia,serveMediaFile,storeInlineProductImage} from '../lib/r2-media.mjs';
function bucket(){const m=new Map();return {m,async get(k){const o=m.get(k);return o?{...o,body:o.bytes,arrayBuffer:async()=>o.bytes,json:async()=>JSON.parse(o.bytes.toString())}:null;},async put(k,b,opt={}){m.set(k,{bytes:Buffer.from(b),httpMetadata:opt.httpMetadata,customMetadata:opt.customMetadata});return {};}};}
test('only media fields are rewritten, missing sources stay intact',()=>{const a='https://sapo.dktcdn.net/a.png',b='private/old.pdf';const input={image:a,note:a,attachments:[{url:b}],Logo:'unavailable/logo.png'};assert.deepEqual([...mediaSources(input)],[a,b,'unavailable/logo.png']);const out=rewriteMedia(input,{[mediaId(a)]:{}});assert.match(out.image,/api\/staff\/media-file/);assert.equal(out.note,a);assert.equal(out.Logo,input.Logo);assert.equal(out.attachments[0].url,b);});
test('inline uploads are verified and reused without extra bytes',async()=>{const b=bucket(),source='data:image/png;base64,aGVsbG8=';const url=await storeInlineProductImage(b,source);assert.match(url,/key=[a-f0-9]{64}$/);await copyMedia(b,source);assert.equal(b.m.size,1);const r=await serveMediaFile(b,mediaId(source));assert.equal(await r.text(),'hello');assert.equal(r.headers.get('cache-control'),'private, max-age=86400');assert.equal((await serveMediaFile(b,'../../pdf/private')).status,404);});
test('unapproved hosts and redirects never get fetched',async()=>{const b=bucket();let calls=0;const fetcher=async()=>{calls++;return new Response('',{status:302,headers:{location:'http://127.0.0.1/private'}});};await assert.rejects(copyMedia(b,'https://127.0.0.1/x',fetcher));assert.equal(calls,0);await assert.rejects(copyMedia(b,'https://sapo.dktcdn.net/x',fetcher));assert.equal(calls,1);assert.equal(b.m.size,0);});
test('HTML sign-in responses are not stored as images',async()=>{const b=bucket();await assert.rejects(copyMedia(b,'https://drive.google.com/x',async()=>new Response('<html>login</html>',{headers:{'content-type':'text/html'}})));assert.equal(b.m.size,0);});
test('cached AppSheet images can be migrated without source login',async()=>{const b=bucket(),s='SanPham_Images/a.png';await b.put('vigifts-media/'+mediaId(s)+'.png','abc',{httpMetadata:{contentType:'image/png'}});const r=await copyMedia(b,s,()=>{throw Error('must not fetch');});assert.equal(r.size,3);});
