import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {Miniflare} from 'miniflare';
import {reportSapoOptions,reportPeriod,mapSapoOrder,summarizeCash,reconcileCash,openReportShift,saveCashShift,saveWorkReport,workHistory,reviewWorkReport,reviewCashShift,workShiftDetails,workCashLedger,syncWorkOrders,workAssistant} from '../lib/work-reports.mjs';
const a={id:'a',role:'employee',position_id:'sale'},b={id:'b',role:'employee',position_id:'sale'},boss={id:'boss',role:'manager',position_id:'manager'};
test('Vietnam shift boundaries and strict dates',()=>{assert.equal(reportPeriod({date:'2026-09-28',start:'08:00',end:'12:00'}).from,'2026-09-28T01:00:00.000Z');assert.throws(()=>reportPeriod({date:'2026-02-30',start:'08:00',end:'12:00'}));assert.throws(()=>reportPeriod({date:'2026-09-28',start:'12:00',end:'08:00'}));});
test('orders require branch and role account membership; payment is not completion',()=>{const base={id:1,location_id:10,assignee_id:11,created_on:'2026-09-28T02:00:00Z',modified_on:'2026-09-28T02:30:00Z',status:'draft',total:100,total_paid:100};const names=new Map([['11','Nhân viên A']]),map=o=>mapSapoOrder(o,new Set(['11','12']),'11','10','2026-09-28T01:00:00Z','2026-09-28T05:00:00Z',names);assert.equal(map(base).status,'processing');assert.equal(map(base).salesName,'Nhân viên A');assert.equal(map({...base,status:'finalized'}).status,'processing');assert.equal(map({...base,location_id:20}),null);assert.equal(map({...base,assignee_id:99}),null);assert.equal(map({...base,assignee_id:12}).own,false);assert.equal(map({...base,status:'cancelled'}).status,'cancelled');assert.equal(map({...base,created_on:'2026-09-27T00:00:00Z'}).newInShift,false);});
test('cash only counts explicit posted cash; unrecognized or undated transactions block match',()=>{const r={id:1,location_id:10,order_id:1,paid_on:'2026-09-28T02:00:00Z',status:'paid',payment_method_name:'Tiền mặt',amount:100};const calc=(list,out=[],options={})=>summarizeCash(list,out,'10','2026-09-28T01:00:00Z','2026-09-28T05:00:00Z',options);assert.deepEqual([calc([r]).incoming,calc([r]).complete],[100,true]);assert.equal(calc([{...r,payment_method_name:'Chuyển khoản'}]).incoming,0);assert.equal(calc([{...r,payment_method_name:''}]).complete,false);assert.equal(calc([{...r,paid_on:null,created_on:r.paid_on}]).complete,false);assert.equal(calc([r,r]).complete,false);assert.equal(calc([r],[{...r,id:2,amount:20}]).outgoing,20);assert.equal(calc([r],[],{orderIds:new Set(['1'])}).incoming,100);assert.equal(calc([{...r,order_id:2}],[],{orderIds:new Set(['1'])}).incoming,0);assert.equal(calc([{...r,order_id:null}],[],{orderIds:new Set(['1'])}).complete,false);assert.equal(reconcileCash(100,100,20,180,false).status,'unverified');assert.equal(reconcileCash(100,100,20,180,true).status,'matched');});
test('D1 shared cash, isolation, report lifecycle, stale writes, handover and audit',async()=>{
 const mf=new Miniflare({modules:true,script:'export default {fetch(){return new Response("ok")}}',compatibilityDate:'2026-05-01',d1Databases:['DB']});
 try{const db=await mf.getD1Database('DB'),env={DB:db,SAPO_ADMIN_COOKIE:'test'};
 for(const file of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())for(const sql of readFileSync('drizzle/'+file,'utf8').split('--> statement-breakpoint'))if(sql.trim())await db.prepare(sql).run();
 for(const p of ['sale','manager'])await db.prepare('INSERT OR IGNORE INTO staff_positions(id,name) VALUES(?,?)').bind(p,p).run();
 for(const m of [a,b,boss])await db.prepare('INSERT INTO staff_members(id,email,name,role,position_id,created_at) VALUES(?,?,?,?,?,?)').bind(m.id,m.id+'@test.vn',m.id,m.role,m.position_id,'2026-09-28').run();
 await db.prepare("INSERT INTO work_branches(id,name,keeper_id,updated_at) VALUES('10','CN 10','a','now')").run();
 await db.prepare("INSERT INTO work_branches(id,name,keeper_id,updated_at) VALUES('20','CN 20',NULL,'now')").run();
 for(const [m,id] of [[a,'11'],[b,'12']])await db.prepare('INSERT INTO work_assignments(member_id,branch_id,sapo_account_id,updated_at) VALUES(?,?,?,?)').bind(m.id,'10',id,'now').run();
 const selection={branchId:'10',date:'2026-09-28',start:'08:00',end:'12:00'};
 let s=await openReportShift(env,a,selection);assert.equal(s.canCash,true);assert.equal((await openReportShift(env,b,selection)).shift.id,s.shift.id);
 await assert.rejects(()=>openReportShift(env,b,{...selection,branchId:'20'}));
 await assert.rejects(()=>saveCashShift(env,b,{shiftId:s.shift.id,revision:1,action:'open',opening:100,acceptHandover:true}));
 s=await saveCashShift(env,a,{shiftId:s.shift.id,revision:1,action:'open',opening:100,acceptHandover:true});
 assert.equal(s.shift.cash_status,'open');assert.equal((await workShiftDetails(env,b,s.shift.id)).shift.opening,null);
 const overlapping=await openReportShift(env,a,{...selection,start:'09:00',end:'13:00'});
 await assert.rejects(()=>saveCashShift(env,a,{shiftId:overlapping.shift.id,revision:1,action:'open',opening:100,acceptHandover:true}));
 await assert.rejects(()=>saveCashShift(env,a,{shiftId:s.shift.id,revision:s.shift.revision,action:'close',actual:100}));
 const stale=s.shift.revision;
 s=await saveCashShift(env,a,{shiftId:s.shift.id,revision:s.shift.revision,action:'close',actual:90,reason:'Chưa có dữ liệu Sapo, cần kiểm tra'});
 assert.equal(s.shift.data.verification,'unverified');assert.equal(s.shift.difference,-10);
 assert.equal((await workCashLedger(env,a,s.shift.id)).balance,100,'Số dư sổ quỹ phải tính từ đầu ca + thu - chi, không lấy kiểm đếm thực tế');
 await assert.rejects(()=>saveCashShift(env,a,{shiftId:s.shift.id,revision:stale,action:'draft',actual:100}));
 await assert.rejects(()=>saveWorkReport(env,a,{shiftId:s.shift.id,phase:'end',submit:true,data:{tasks:[{title:'Việc 1',done:true}],issues:'Chưa có Sapo'}}));
 s=await saveWorkReport(env,a,{shiftId:s.shift.id,phase:'start',submit:true,data:{tasks:[{title:'Việc 1'}]}});
 const report=s.reports.find(r=>r.phase==='start');
 await assert.rejects(()=>saveWorkReport(env,a,{shiftId:s.shift.id,phase:'start',revision:report.revision,data:{tasks:[{title:'Sửa'}]}}));
 await assert.rejects(()=>reviewWorkReport(env,b,{id:report.id,revision:report.revision,status:'approved'}));
 await reviewWorkReport(env,boss,{id:report.id,revision:report.revision,status:'returned',note:'Bổ sung mục tiêu'});
 s=await saveWorkReport(env,a,{shiftId:s.shift.id,phase:'start',revision:report.revision+1,submit:true,data:{tasks:[{title:'Việc 1'}]}});
 const fetchMock=async url=>{const p=new URL(url).pathname;if(p.endsWith('/orders.json'))return Response.json({orders:[{id:1,location_id:10,assignee_id:11,created_on:'2026-09-28T02:00:00Z',modified_on:'2026-09-28T02:10:00Z',status:'completed',total:100},{id:2,location_id:10,assignee_id:12,created_on:'2026-09-28T02:00:00Z',modified_on:'2026-09-28T02:10:00Z',status:'draft',total:100}]});return Response.json({error:'unavailable'},{status:404});};
 const snap=await syncWorkOrders(env,a,{shiftId:s.shift.id},fetchMock);assert.equal(snap.orders.length,2);assert.equal(snap.orders.filter(x=>x.own).length,1);assert.equal(snap.cash.complete,false);
 const assistant=await workAssistant(env,a,{shiftId:s.shift.id,mode:'start'});assert.ok(assistant.tasks.length>=3);assert.ok(assistant.suggestedContacts>=5);
 s=await saveWorkReport(env,a,{shiftId:s.shift.id,phase:'end',data:{tasks:[{title:'Việc 1',status:'partial'}],cashChecks:{counted:true,mismatch:true,difference:10,reason:'Kiểm tra lại'},issueTags:['Chênh quỹ']}});
 const enhanced=s.reports.find(r=>r.phase==='end').data;assert.equal(enhanced.tasks[0].status,'partial');assert.equal(enhanced.cashChecks.difference,10);assert.deepEqual(enhanced.issueTags,['Chênh quỹ']);
 s=await saveWorkReport(env,a,{shiftId:s.shift.id,phase:'end',revision:s.reports.find(r=>r.phase==='end').revision,submit:true,data:{tasks:[{title:'Việc 1',done:true}]}});
 assert.equal(s.reports.find(r=>r.phase==='end').snapshot.orders.length,2);
 assert.equal((await workHistory(env,b,new URLSearchParams())).reports.length,0);
 const next=await openReportShift(env,a,{...selection,start:'13:00',end:'17:00'});assert.equal(next.previous.actual,90);
 await assert.rejects(()=>saveCashShift(env,a,{shiftId:next.shift.id,revision:1,action:'open',opening:100,acceptHandover:true}));
 await saveCashShift(env,a,{shiftId:next.shift.id,revision:1,action:'open',opening:90,acceptHandover:true});
 await assert.rejects(()=>reviewCashShift(env,boss,{id:s.shift.id,revision:s.shift.revision,action:'reopen',note:'Mở lại'}));
 assert.ok((await db.prepare('SELECT COUNT(*) AS n FROM work_audit').first()).n>=6);
 }finally{await mf.dispose();}
});

test('Sapo branch labels remain visible when locations omit name',async()=>{
 const locations=[{id:1,label:'Bách Ngân'},{id:2,name:'  ',label:'LocknLock'},{id:3,full_name:'Kho tổng'},{id:4,code:'CN04'},{id:5},{id:6,name:'Chi nhánh cũ',status:'inactive'},{id:7,name:'Tên chính',label:'Tên phụ'}];
 const result=await reportSapoOptions({SAPO_ADMIN_COOKIE:'test'},async url=>Response.json(new URL(url).pathname.endsWith('/locations.json')?{locations}:{accounts:[{id:10,full_name:'Nhân viên A'}]}));
 assert.deepEqual(result.locations,[{id:'1',name:'Bách Ngân'},{id:'2',name:'LocknLock'},{id:'3',name:'Kho tổng'},{id:'4',name:'CN04'},{id:'5',name:'Chi nhánh #5'},{id:'7',name:'Tên chính'}]);
 assert.equal(result.accounts[0].id,'10');
});
