'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,Download,Printer,Copy,ExternalLink,Building2,Truck,CreditCard,Package,FileText,Phone,Mail,Check,CalendarDays} from 'lucide-react';
import {quotePayloadFromData,applyDetailsToQuote} from '@/lib/contract-detail.mjs';
import './contract-detail.css';
type Row=Record<string,any>;
const money=(n:number)=>Number(n||0).toLocaleString('vi-VN',{maximumFractionDigits:0})+' ₫';
const date=(s:string)=>s&&!Number.isNaN(Date.parse(s))?new Date(s).toLocaleDateString('vi-VN',{timeZone:'Asia/Ho_Chi_Minh'}):'Chưa ghi nhận';
const value=(v:any)=>v===null||v===undefined||v===''?'Chưa ghi nhận':String(v);
let exportReady:Promise<void>|null=null;
function loadExport(){return exportReady||(exportReady=(async()=>{for(const src of ['/fflate.min.js','/hrc-pdf.js','/contract-document.js'])await new Promise<void>((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=()=>resolve();s.onerror=()=>{s.remove();reject(Error('Chưa tải được công cụ xuất hồ sơ. Vui lòng thử lại.'));};document.head.appendChild(s);});})().catch(e=>{exportReady=null;throw e;}));}
function Field({label,children}:{label:string,children:any}){return <div className="cd-field"><dt>{label}</dt><dd>{value(children)}</dd></div>;}
export default function ContractDetail({revision}:{revision:number}){
 const [record,setRecord]=useState<Row|null>(null),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[downloading,setDownloading]=useState(false),[query,setQuery]=useState(''),[id,setId]=useState('');
 useEffect(()=>{const controller=new AbortController();let active=true;const selected=new URLSearchParams(location.search).get('quoteId')||'';setId(selected);setBusy(true);setError('');setRecord(null);
 (async()=>{if(!selected)throw Error('Thiếu mã hợp đồng. Vui lòng chọn lại từ danh sách.');const r=await fetch('/api/staff/quotes/'+encodeURIComponent(selected),{signal:controller.signal,cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Không tải được hợp đồng.');if(!d.data?.contractDocument?.contractNumber)throw Error('Báo giá này chưa có HĐKT đã sinh.');if(active)setRecord(d);})().catch(e=>{if(active&&e.name!=='AbortError')setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;controller.abort();};},[revision]);
 async function copy(){try{await navigator.clipboard.writeText(record?.data.contractDocument.contractNumber||'');setNotice('Đã sao chép số hợp đồng.');}catch{setNotice('Không thể sao chép tự động. Anh có thể chọn số hợp đồng để sao chép.');}}
 async function download(){setDownloading(true);setNotice('');try{await loadExport();const data=record!.data;await (globalThis as any).ContractDocument.download({quote:applyDetailsToQuote(quotePayloadFromData(data),data.contractDocument.details),contractNumber:data.contractDocument.contractNumber,details:data.contractDocument.details});setNotice('Đã tạo bộ hồ sơ ZIP gồm HĐKT, biên bản nghiệm thu và đề nghị tạm ứng.');}catch(e:any){setNotice(e.message||'Chưa tải được bộ hồ sơ.');}finally{setDownloading(false);}}
 if(busy)return <div className="cd-loading" role="status"><FileText size={30}/><h2>Đang mở hồ sơ hợp đồng</h2><p>Đang kiểm tra quyền và tải dữ liệu đã lưu…</p></div>;
 if(error||!record)return <div className="qw-error" role="alert">{error||'Không có dữ liệu hợp đồng.'}<a href="/contracts">Quay lại danh sách HĐKT</a></div>;
 const d=record.data,doc=d.contractDocument,details=doc.details||{},payload=quotePayloadFromData(d),total=payload.total;
 const rate=Number(details.depositRate),validRate=details.depositRate!==undefined&&details.depositRate!==null&&Number.isFinite(rate)&&rate>=0&&rate<=100,deposit=validRate?Math.round(total*rate/100):null;
 const norm=(s:any)=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[đĐ]/g,'d').toLowerCase();
 const products=payload.items.filter((p:Row)=>norm(p.name+' '+p.sku).includes(norm(query)));
 return <div className="cd-page"><a className="cd-back" href="/contracts"><ArrowLeft size={16}/> HĐKT đã sinh</a>
 <section className="cd-hero"><div className="cd-hero-top"><span className="cd-eyebrow"><FileText size={16}/> HỒ SƠ HỢP ĐỒNG KINH TẾ</span><span className="cd-saved"><Check size={14}/> Đã sinh HĐKT</span></div><h2>{doc.contractNumber}</h2><p className="cd-customer">{details.name||d.customer||'Chưa ghi nhận khách hàng'}</p><div className="cd-meta"><span><CalendarDays size={14}/> Ngày sinh: {date(doc.generatedAt)}</span><span>Phụ trách: {d.owner||record.creatorName||'Chưa ghi nhận'}</span><span>Báo giá {record.approvalStatus==='approved'?'đã duyệt':'đợi duyệt'}</span></div>
 <div className="cd-actions"><button className="cd-primary" onClick={download} disabled={downloading}><Download size={17}/>{downloading?'Đang tạo hồ sơ…':'Tải bộ hồ sơ'}</button><button onClick={()=>window.print()}><Printer size={17}/> In thông tin</button><button onClick={copy}><Copy size={17}/> Sao chép số HĐ</button><a href={'/quote?quoteId='+encodeURIComponent(id)}><ExternalLink size={17}/> {record.canEdit?'Mở / chỉnh báo giá gốc':'Xem báo giá gốc'}</a></div></section>
 {notice&&<p className="cd-notice" role="status">{notice}</p>}
 <div className="cd-metrics"><div><span>Giá trị hợp đồng</span><strong>{money(total)}</strong><small>Đã bao gồm VAT</small></div><div><span>Tạm ứng theo điều khoản</span><strong>{deposit===null?'Chưa ghi nhận':money(deposit)}</strong><small>{validRate?rate+'% giá trị hợp đồng':'Chưa có tỷ lệ tạm ứng'}</small></div><div><span>Phần còn lại theo điều khoản</span><strong>{deposit===null?'Chưa ghi nhận':money(total-deposit)}</strong><small>Không phải số dư công nợ thực tế</small></div></div>
 <nav className="cd-jump" aria-label="Các phần của hợp đồng"><a href="#cd-customer">Khách hàng</a><a href="#cd-products">Sản phẩm ({payload.items.length})</a><a href="#cd-terms">Điều khoản</a><a href="#cd-files">Hồ sơ</a></nav>
 <div className="cd-columns"><div className="cd-main-column"><section className="cd-panel" id="cd-customer"><h3><Building2 size={19}/> Thông tin khách hàng</h3><dl className="cd-fields"><Field label="Tên đơn vị">{details.name||d.customer}</Field><Field label="Mã số thuế">{details.taxCode||d.customerTaxCode}</Field><Field label="Mã khách hàng">{details.customerCode||d.customerCode}</Field><Field label="Người đại diện">{details.representativeName}</Field><Field label="Chức vụ">{details.representativeTitle}</Field><Field label="Địa chỉ">{details.address||d.customerAddress}</Field></dl><div className="cd-contact">{d.phone&&<a href={'tel:'+String(d.phone).replace(/[^+\d]/g,'')}><Phone size={16}/>{d.phone}</a>}{d.email&&<a href={'mailto:'+d.email}><Mail size={16}/>{d.email}</a>}</div></section>
 <section className="cd-panel" id="cd-products"><div className="cd-section-heading"><h3><Package size={19}/> Danh mục sản phẩm</h3><span>{payload.items.length} dòng</span></div><label className="cd-search">Tìm trong hợp đồng<input type="search" placeholder="Tên sản phẩm hoặc SKU" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="cd-product-list">{products.map((p:Row)=><article className="cd-product" key={p.line}><div className="cd-product-title"><span className="cd-index">{p.line}</span><div><strong>{p.name||'Sản phẩm'}</strong><small>{p.sku||'Chưa có mã'} · {p.unit||'SP'}</small></div></div>{p.description&&<p>{p.description}</p>}<div className="cd-product-numbers"><div><span>Số lượng</span><b>{Number(p.quantity).toLocaleString('vi-VN')}</b></div><div><span>Đơn giá sau CK</span><b>{money(p.price_after_discount)}</b></div><div><span>VAT</span><b>{p.tax_percent}%</b></div><div><span>Thành tiền trước VAT</span><b>{money(p.line_total)}</b></div></div><div className="cd-product-footer"><span>{p.status}</span><span>{p.delivery_date?'Hẹn giao: '+date(p.delivery_date):'Chưa có ngày hẹn giao'}</span></div></article>)}{!products.length&&<p className="qw-empty">Không có sản phẩm phù hợp.</p>}</div><dl className="cd-totals"><Field label="Tổng trước VAT">{money(payload.subtotal)}</Field><Field label="Thuế VAT">{money(payload.vat_amount)}</Field><Field label="Tổng giá trị hợp đồng">{money(total)}</Field></dl></section>
 {d.notes&&<section className="cd-panel"><h3><FileText size={19}/> Ghi chú đã lưu</h3><p className="cd-notes">{d.notes}</p></section>}</div>
 <aside className="cd-side-column" id="cd-terms"><section className="cd-panel"><h3><Truck size={19}/> Giao nhận</h3><dl><Field label="Địa điểm giao hàng">{details.deliveryAddress}</Field><Field label="Thời gian giao hàng">{details.deliveryTime}</Field></dl></section><section className="cd-panel"><h3><CreditCard size={19}/> Thanh toán</h3><dl><Field label="Phương thức">{details.paymentMethod}</Field><Field label="Tỷ lệ tạm ứng">{validRate?rate+'%':null}</Field><Field label="Thời hạn thanh toán">{details.paymentDays!==undefined?details.paymentDays+' ngày':null}</Field><Field label="Tài khoản thu tiền">{details.collectionAccountName}</Field></dl><p className="cd-footnote">Điều khoản tại thời điểm sinh hợp đồng. Tiền đã thu và công nợ được theo dõi trong CRM.</p></section><section className="cd-panel" id="cd-files"><h3><FileText size={19}/> Hồ sơ & nguồn dữ liệu</h3><dl><Field label="Pháp nhân">{details.legalEntity}</Field><Field label="Báo giá gốc">{doc.quoteNo||d.quoteNo}</Field><Field label="Ngày báo giá">{date(d.date)}</Field></dl><p className="cd-footnote">Bộ hồ sơ ZIP gồm 3 tệp Word: HĐKT, biên bản bàn giao/nghiệm thu và đề nghị tạm ứng, theo mẫu hiện tại.</p><button className="cd-file-button" onClick={download} disabled={downloading}><Download size={16}/> Tải bộ hồ sơ</button></section></aside></div>
 <div className="cd-mobile-actions"><a href="/contracts"><ArrowLeft size={18}/>Danh sách</a><button onClick={download} disabled={downloading}><Download size={18}/>{downloading?'Đang tạo…':'Tải hồ sơ'}</button><button onClick={copy}><Copy size={18}/>Sao chép</button></div>
 </div>;
}
