'use client';
import {useEffect,useRef,useState} from 'react';
import {X,Save,Printer,Download,RefreshCw} from 'lucide-react';
import {loadExport} from '@/lib/contract-export-client';
import {quotePayloadFromData,applyDetailsToQuote} from '@/lib/contract-detail.mjs';
import './contract-document-editor.css';
type Row=Record<string,any>;
const fields=[['name','Tên bên mua'],['customerCode','Mã khách hàng'],['taxCode','Mã số thuế'],['representativeName','Người đại diện'],['representativeTitle','Chức vụ'],['address','Địa chỉ bên mua'],['deliveryAddress','Địa điểm giao hàng'],['deliveryTime','Thời gian giao hàng'],['paymentMethod','Phương thức thanh toán'],['depositRate','Tạm ứng (%)'],['paymentDays','Hạn thanh toán (ngày)'],['collectionAccountName','Tài khoản thu tiền']];
export default function ContractDocumentEditor({record,onSaved,onClose}:{record:Row,onSaved:(r:Row)=>void,onClose:()=>void}){
 const [wordEdits,setWordEdits]=useState<Row[]>(()=>record.data.contractDocument.wordEdits||[]),[showFields,setShowFields]=useState(false),[selected,setSelected]=useState<number|null>(null);
 const editsRef=useRef(wordEdits);editsRef.current=wordEdits;
 const [base,setBase]=useState(record),[details,setDetails]=useState<Row>(()=>structuredClone(record.data.contractDocument.details||{})),[busy,setBusy]=useState(false),[rendering,setRendering]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[bytes,setBytes]=useState<Uint8Array|null>(null),[previewRevision,setPreviewRevision]=useState(0),[renderedDetails,setRenderedDetails]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),frame=useRef<HTMLIFrameElement>(null);
 const detailsKey=JSON.stringify([details,wordEdits]);
 const dirty=JSON.stringify(details)!==JSON.stringify(base.data.contractDocument.details||{})||JSON.stringify(wordEdits)!==JSON.stringify(base.data.contractDocument.wordEdits||[]);
 const printable=!!bytes&&!dirty&&!rendering&&renderedDetails===detailsKey;
 const latestDirty=useRef(dirty);latestDirty.current=dirty;
 useEffect(()=>{dialog.current?.showModal();const leave=(e:BeforeUnloadEvent)=>{if(latestDirty.current){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[]);
 function close(){if(busy)return;if(dirty&&!window.confirm('Bỏ các điều chỉnh chưa lưu?'))return;onClose();}
 useEffect(()=>{let active=true;setBytes(null);setRenderedDetails('');setRendering(true);setError('');
 (async()=>{await loadExport();const d=base.data,doc=d.contractDocument;const response=await fetch(d.type==='VIGIFTS'?'/mau-hop-dong-vigifts-hdkt.docx':d.type==='HRC'?'/mau-hop-dong-hrc-hdkt.docx':'/mau-hop-dong-b2b-hdkt.docx',{cache:'no-store'});if(!response.ok)throw Error('Không tải được mẫu HĐKT.');const output=await (globalThis as any).ContractDocument.build({quote:{...applyDetailsToQuote(quotePayloadFromData(d),details),contract_word_edits:[]},contractNumber:doc.contractNumber,details,templateBytes:await response.arrayBuffer(),documentType:'HDKT'});
 const prepared=await (globalThis as any).ContractWordEdit.prepare(output,wordEdits);
 const {renderAsync}=await import('docx-preview');if(!active)return;const f=frame.current,document=f?.contentDocument;if(!document)throw Error('Không mở được khung xem HĐKT.');document.open();document.write('<!doctype html><html lang="vi"><head><meta charset="utf-8"><title>Hợp đồng kinh tế</title><style>body{margin:0;background:#edf0f5} .docx-wrapper{padding:16px!important} @media print{@page{size:A4;margin:0}body{background:white}.docx-wrapper{padding:0!important;zoom:1!important}section.docx{box-shadow:none!important;margin:0!important;break-after:page}section.docx:last-child{break-after:auto}}</style></head><body><main></main></body></html>');document.close();await renderAsync(prepared.preview,document.querySelector('main')!,undefined,{inWrapper:true,hideWrapperOnPrint:true,breakPages:true,ignoreLastRenderedPageBreak:false,renderAltChunks:false,useBase64URL:true});
 await document.fonts.ready;await Promise.all(Array.from(document.images).map(image=>image.complete?Promise.resolve():new Promise(resolve=>{image.onload=resolve;image.onerror=resolve;})));
 if(!active)return;const wrapper=document.querySelector('.docx-wrapper') as HTMLElement|null;if(wrapper)wrapper.style.zoom=String(Math.min(1,Math.max(.3,((f?.clientWidth||800)-32)/794)));if(base.canEdit)for(const info of prepared.paragraphs){const marker=document.getElementById('bnword_'+info.index),p=marker?.closest('p');if(!p)continue;
 p.contentEditable='plaintext-only';p.setAttribute('aria-label','Đoạn hợp đồng có thể chỉnh');p.dataset.wordIndex=String(info.index);p.dataset.wordHash=info.hash;p.style.outlineOffset='3px';
 p.addEventListener('focus',()=>{setSelected(info.index);p.style.outline='1px solid #6388c5';});p.addEventListener('blur',()=>p.style.outline='');
 p.addEventListener('input',()=>{const edit={...(editsRef.current.find(e=>e.index===info.index)||{}),index:info.index,hash:info.hash,text:p.innerText};setWordEdits(old=>[...old.filter(e=>e.index!==info.index),edit].sort((a,b)=>a.index-b.index));});}
 setBytes(prepared.bytes);setRenderedDetails(JSON.stringify([details,wordEdits]));
 })().catch(e=>{if(active)setError(e.message||'Không dựng được bản xem HĐKT.');}).finally(()=>{if(active)setRendering(false);});return()=>{active=false;};
 // Preview is explicitly regenerated, so typing never steals focus or changes the page mid-edit.
 },[base,previewRevision]);
 async function save(){if(!dirty)return;setBusy(true);setError('');setMessage('');try{
 const deposit=Number(details.depositRate),days=Number(details.paymentDays);if(details.depositRate===''||!Number.isFinite(deposit)||deposit<0||deposit>100)throw Error('Tỷ lệ tạm ứng phải từ 0 đến 100%.');if(details.paymentDays===''||!Number.isInteger(days)||days<0||days>3650)throw Error('Hạn thanh toán phải từ 0 đến 3650 ngày.');
 const cleaned={...details,depositRate:deposit,paymentDays:days};const data={...base.data,contractDocument:{...base.data.contractDocument,details:cleaned,wordEdits}};
 const response=await fetch('/api/staff/quotes/'+encodeURIComponent(base.id)+'/contract-details',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({details:cleaned,wordEdits,revision:base.revision})});const result=await response.json();if(!response.ok)throw Error(response.status===409?'Hợp đồng đã thay đổi ở nơi khác. Hãy sao chép phần vừa chỉnh rồi đóng và tải lại trang trước khi lưu.':result.error||'Không lưu được hợp đồng.');
 const savedDetails=result.details||cleaned;data.contractDocument.details=savedDetails;data.contractDocument.wordEdits=result.wordEdits||[];setWordEdits(result.wordEdits||[]);const updated={...base,...result,data};setDetails(savedDetails);setBase(updated);onSaved(updated);setMessage('Đã lưu điều chỉnh. Đang cập nhật bản xem để in và tải Word.');
 }catch(e:any){setError(e.message);}finally{setBusy(false);}}
 function format(key:string,value:any){if(selected===null)return;const p=frame.current?.contentDocument?.querySelector('[data-word-index="'+selected+'"]') as HTMLElement|null;if(!p)return;
 const edit={...(editsRef.current.find(e=>e.index===selected)||{}),index:selected,hash:p.dataset.wordHash,text:p.innerText,[key]:value};setWordEdits(old=>[...old.filter(e=>e.index!==selected),edit].sort((a,b)=>a.index-b.index));if(key==='bold')p.style.fontWeight=value?'bold':'normal';if(key==='italic')p.style.fontStyle=value?'italic':'normal';if(key==='underline')p.style.textDecoration=value?'underline':'none';if(key==='align')p.style.textAlign=value==='both'?'justify':value;
 }
 function resetWord(){if(!window.confirm('Bỏ tất cả chỉnh sửa trực tiếp và dựng lại từ thông tin hợp đồng? Chỉ được lưu sau khi anh bấm Lưu điều chỉnh.'))return;setWordEdits([]);setSelected(null);setPreviewRevision(n=>n+1);}
 async function download(){if(!bytes||!printable)return;const blob=new Blob([new Uint8Array(bytes)],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});const filename='HDKT_'+String(base.data.contractDocument.contractNumber).replace(/[^\p{L}\p{N}_-]/gu,'-')+'.docx';setBusy(true);try{const modulePath='/r2-export.js';const exporter=await import(/* @vite-ignore */ modulePath);await exporter.saveExport(blob,filename);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e:any){setError(e.message||'Không tải được file Word.');}finally{setBusy(false);}}
 return <dialog ref={dialog} className="cde-dialog" onCancel={e=>{e.preventDefault();close();}}><header><div><small>SOẠN HĐKT · {base.data.type}</small><h2>{base.data.contractDocument.contractNumber}</h2></div><button onClick={close} aria-label="Đóng xem hợp đồng" disabled={busy}><X size={20}/></button></header>
 <div className="cde-toolbar"><button onClick={()=>setShowFields(v=>!v)}>Thông tin điền mẫu</button>{base.canEdit&&<button className="cde-primary" onClick={save} disabled={busy||!dirty}><Save size={16}/>{busy?'Đang lưu…':'Lưu điều chỉnh'}</button>}<button onClick={()=>setPreviewRevision(n=>n+1)} disabled={busy||rendering}><RefreshCw size={16}/>Cập nhật bản xem</button><button onClick={()=>{frame.current?.contentWindow?.focus();frame.current?.contentWindow?.print();}} disabled={!printable||busy}><Printer size={16}/>In HĐKT</button><button onClick={download} disabled={!printable||busy}><Download size={16}/>Tải Word HĐKT</button><span>{dirty?'Có thay đổi chưa lưu':'Nội dung đã lưu'}</span></div>
 {base.canEdit&&<div className="cde-format"><span>Định dạng đoạn:</span>{[['bold','Đậm'],['italic','Nghiêng'],['underline','Gạch chân']].map(([key,label])=><button key={key} disabled={selected===null||busy} aria-pressed={!!wordEdits.find(e=>e.index===selected)?.[key]} onClick={()=>format(key,!wordEdits.find(e=>e.index===selected)?.[key])}>{label}</button>)}<select aria-label="Căn lề đoạn" disabled={selected===null||busy} onChange={e=>format('align',e.target.value)} value={wordEdits.find(e=>e.index===selected)?.align||'left'}><option value="left">Trái</option><option value="center">Giữa</option><option value="right">Phải</option><option value="both">Đều</option></select><button disabled={!wordEdits.length||busy} onClick={resetWord}>Dựng lại từ thông tin</button></div>}
 {error&&<p className="cde-alert" role="alert">{error}</p>}{message&&<p className="cde-message" role="status">{message}</p>}
 <div className={"cde-layout "+(!showFields?"cde-document-only":"")}>{showFields&&<section className="cde-form"><h3>Thông tin hợp đồng</h3><p>Điều chỉnh các thông tin điền vào mẫu Word. Lưu trước khi in hoặc tải file. Chỉnh văn bản trực tiếp ở trang giấy bên cạnh. Thay đổi văn bản không cập nhật số liệu báo giá gốc. Khi đã chỉnh trực tiếp, cần dựng lại để thay thông tin điền mẫu.</p>{fields.map(([key,label])=><label key={key}>{label}{['address','deliveryAddress','deliveryTime','paymentMethod'].includes(key)?<textarea disabled={!base.canEdit||busy||wordEdits.length>0} rows={3} value={details[key]??''} onChange={e=>setDetails(d=>({...d,[key]:e.target.value}))}/>:<input disabled={!base.canEdit||busy||wordEdits.length>0} type={['depositRate','paymentDays'].includes(key)?'number':'text'} min={0} max={key==='depositRate'?100:key==='paymentDays'?3650:undefined} value={details[key]??''} onChange={e=>setDetails(d=>({...d,[key]:e.target.value}))}/>}</label>)}{!base.canEdit&&<p>Chế độ chỉ xem. Tài khoản chưa có quyền chỉnh hợp đồng này.</p>}</section>}<section className="cde-preview"><p>{rendering?'Đang dựng bản xem từ file Word…':dirty?'Bản nháp: bấm Cập nhật bản xem để xem điều chỉnh, bấm Lưu để in/tải.':'Bấm vào đoạn văn hoặc ô bảng để chỉnh trực tiếp. Lưu xong mới in/tải Word.'} Sửa văn bản không tự tính lại giá, thuế hoặc số liệu báo giá. Ngắt trang có thể khác Microsoft Word.</p><iframe ref={frame} title="Nội dung file Word HĐKT" sandbox="allow-same-origin allow-modals"/></section></div>
 </dialog>;
}
