'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,Building2,Package,FileText,Wallet,Phone,Mail} from 'lucide-react';
import './entity-detail.css';
type Row=Record<string,any>;
const money=(v:any)=>Number(v||0).toLocaleString('vi-VN')+' ₫';
const day=(v:any)=>v?String(v).slice(0,10).split('-').reverse().join('/'):'Chưa ghi nhận';
export default function EntityDetail({kind,revision}:{kind:'customer'|'product',revision:number}){
 const [data,setData]=useState<Row|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('overview'),[query,setQuery]=useState(''),[limit,setLimit]=useState(30);
 useEffect(()=>{const c=new AbortController();setError('');setData(null);const id=new URLSearchParams(location.search).get(kind==='customer'?'id':'sku')||'';(async()=>{if(!id)throw Error('Thiếu mã hồ sơ. Vui lòng chọn lại từ danh sách.');const r=await fetch('/api/staff/entity-detail?kind='+kind+'&id='+encodeURIComponent(id)+(revision?'&refresh=1':''),{signal:c.signal,cache:'no-store',credentials:'include'});const d=await r.json();if(r.status===401){location.replace('/login.html?returnTo='+encodeURIComponent(location.pathname+location.search+location.hash));return;}if(!r.ok)throw Error(d.error||'Không tải được hồ sơ');setData(d);})().catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[kind,revision]);
 if(error)return <div className="qw-error" role="alert">{error}<a href={kind==='customer'?'/customers':'/products'}>Quay lại danh sách</a></div>;
 if(!data)return <p className="qw-empty" role="status">Đang tổng hợp hồ sơ trong phạm vi tài khoản…</p>;
 const customer=kind==='customer',e=data.entity,s=data.summary,debt=data.debt,quotes=data.quotes.filter((q:Row)=>(tab!=='contracts'||q.contractNumber)&&[q.quoteNo,q.contractNumber,q.customer].join(' ').toLocaleLowerCase().includes(query.toLocaleLowerCase()));
 const tabs=customer?[['overview','Tổng quan'],['quotes','Báo giá'],['contracts','HĐKT'],['products','Sản phẩm'],['debt','Công nợ']]:[['overview','Tổng quan'],['quotes','Báo giá'],['contracts','HĐKT'],['customers','Khách hàng']];
 return <div className="ed-page"><a className="ed-back" href={customer?'/customers':'/products'}><ArrowLeft size={16}/>Danh sách {customer?'khách hàng':'sản phẩm'}</a><section className="ed-hero"><div className="ed-icon">{customer?<Building2/>:<Package/>}</div><div><p>{customer?'HỒ SƠ KHÁCH HÀNG':'HỒ SƠ SẢN PHẨM'}</p><h2>{e.name}</h2><span>{customer?[e.customerCode,e.taxCode&&'MST '+e.taxCode].filter(Boolean).join(' · '):[e.sku,e.brand,e.unit].filter(Boolean).join(' · ')}</span></div></section>
 <div className="ed-stats">{[['Báo giá',s.quoteCount],['HĐKT đã sinh trên web',s.contractCount],[customer?'Sản phẩm':'Khách hàng',customer?s.productCount:s.customerCount],['Giá trị các báo giá',money(s.quotedValue)]].map(([k,v])=><div key={k}><small>{k}</small><strong>{v}</strong></div>)}</div><p className="qw-muted">Thống kê theo các báo giá tài khoản được phép xem. Giá trị báo giá không phải doanh thu đã thu; số lượng là tổng trên hồ sơ, không phải số đã giao.</p>
 <nav className="ed-tabs" aria-label="Nội dung hồ sơ">{tabs.map(([key,label])=><button key={key} onClick={()=>{setTab(key);setLimit(30);setQuery('');}} aria-pressed={tab===key}>{label}</button>)}</nav>
 {tab==='overview'&&<div className="ed-grid"><section className="ed-panel"><h3>{customer?'Thông tin liên hệ':'Thông tin sản phẩm'}</h3>{customer?<><p>{e.address||'Chưa có địa chỉ'}</p><p>Người liên hệ: {e.contact||'Chưa ghi nhận'}</p><div className="ed-links">{e.phone&&<a href={'tel:'+String(e.phone).replace(/[^+\d]/g,'')}><Phone size={15}/>{e.phone}</a>}{e.email&&<a href={'mailto:'+e.email}><Mail size={15}/>{e.email}</a>}</div><small>Ngày tạo: {day(e.createdAt)}</small></>:<><p>Quy cách: {e.perCarton||'—'} {e.unit||'SP'}/thùng</p><div className="ed-stats">{data.policies.map((p:any,i:number)=><div key={i}><small>{typeof p==='string'?p:p.name}</small><strong>{e.prices?.[i]!=null?money(e.prices[i]):'Chưa có giá'}</strong></div>)}</div></>}</section><section className="ed-panel"><h3>{customer?'Công nợ theo CRM':'Tồn kho hiện tại'}</h3>{customer?<>{debt?.fallback&&<p className="qw-error">Số liệu từ bản lưu CRM ngày {day(debt.asOf)}.</p>}{debt?.available?<><strong className="ed-amount">{money(debt.balance)}</strong><p>Giá trị HĐKT: {money(debt.value)} · Đã thu: {money(debt.paid)}</p><button className="qw-load-more" onClick={()=>setTab('debt')}>Xem đối chiếu công nợ</button></>:<p>{debt?.reason||'Chưa có số liệu công nợ'}</p>}</>:<ul className="ed-stock">{data.warehouses.map((w:any,i:number)=><li key={i}><span>{typeof w==='string'?w:w.name}</span><b>{Number(e.stock?.[i]||0).toLocaleString('vi-VN')} {e.unit||'SP'}</b></li>)}</ul>}</section></div>}
 {(tab==='quotes'||tab==='contracts')&&<section className="ed-panel"><h3><FileText size={18}/>{tab==='quotes'?'Báo giá liên quan':'Hợp đồng đã sinh trên web'}</h3><input className="ed-search" aria-label="Tìm hồ sơ" placeholder="Tìm số báo giá, số HĐKT, khách hàng" value={query} onChange={e=>{setQuery(e.target.value);setLimit(30);}}/><ul className="ed-list">{quotes.slice(0,limit).map((q:Row)=><li key={q.id}><a href={(tab==='contracts'?'/contracts/detail?quoteId=':'/quote?quoteId=')+encodeURIComponent(q.id)}><div><b>{tab==='contracts'?q.contractNumber:q.quoteNo}</b><p>{q.customer}</p><small>{q.owner} · {day(q.updatedAt)}</small></div><strong>{money(q.total)}</strong></a><div className="ed-lines">{q.rows.filter((r:Row)=>customer||String(r.sku).toUpperCase()===String(e.sku).toUpperCase()).map((r:Row,i:number)=><p key={i}>{r.name} · {r.qty} {r.unit} {q.contractNumber&&<>· Giao: {r.delivery.date?day(r.delivery.date):r.delivery.reason}</>}</p>)}</div></li>)}</ul>{!quotes.length&&<p className="qw-empty">Chưa có hồ sơ phù hợp</p>}{quotes.length>limit&&<button className="qw-load-more" onClick={()=>setLimit(n=>n+30)}>Xem thêm</button>}</section>}
 {tab==='products'&&<section className="ed-panel"><h3>Sản phẩm đã báo giá</h3><ul className="ed-list">{data.products.map((p:Row,i:number)=><li key={i}><a href={p.sku?'/products/detail?sku='+encodeURIComponent(p.sku):undefined}><div><b>{p.name}</b><small>{p.sku||'Chưa có SKU'} · {p.quoteCount} báo giá</small></div><span>{p.quoteQuantity} {p.unit} báo giá<br/>{p.contractQuantity} {p.unit} trong HĐKT</span></a></li>)}</ul>{!data.products.length&&<p className="qw-empty">Chưa có sản phẩm liên quan</p>}</section>}
 {tab==='customers'&&<section className="ed-panel"><h3>Khách hàng đã được báo giá sản phẩm</h3><ul className="ed-list">{data.customers.map((c:Row,i:number)=><li key={i}><a href={c.id?'/customers/detail?id='+encodeURIComponent(c.id):undefined}><b>{c.name||'Chưa ghi nhận khách hàng'}</b><span>{c.code}</span></a></li>)}</ul>{!data.customers.length&&<p className="qw-empty">Chưa có khách hàng liên quan</p>}</section>}
 {tab==='debt'&&<section className="ed-panel"><h3><Wallet size={18}/>Đối chiếu công nợ CRM</h3>{debt?.fallback&&<p className="qw-error">Bản lưu CRM ngày {day(debt.asOf)}, chưa phải số liệu trực tiếp.</p>}{debt?.available?<><div className="ed-stats">{[['Giá trị HĐKT CRM',debt.value],['Đã thu theo sổ thu chi',debt.paid],['Còn phải thu / dư tiền',debt.balance]].map(([k,v])=><div key={k}><small>{k}</small><strong>{money(v)}</strong></div>)}</div><p>{debt.contractCount} HĐKT CRM được đối chiếu theo mã khách hàng/MST. Số âm là dư tiền. Cập nhật: {day(debt.asOf)}.</p><ul className="ed-list">{debt.contracts.map((c:Row)=><li key={c.id}><div className="ed-payment"><div><b>{c.number}</b>{c.deliveryDate&&<p>Ngày hẹn giao: {day(c.deliveryDate)}</p>}</div><span>{money(c.value)}</span></div></li>)}</ul><h3>Lịch sử thu tiền</h3><ul className="ed-list">{debt.payments.map((p:Row)=><li key={p.id}><div className="ed-payment"><span>{day(p.date)} · {p.note}</span><b>{money(p.amount)}</b></div></li>)}</ul>{!debt.payments.length&&<p>Chưa ghi nhận khoản thu trong dữ liệu CRM này.</p>}</>:<p className="qw-empty">{debt?.reason||'Chưa đủ dữ liệu đối chiếu công nợ'}</p>}</section>}
 </div>;
}
